POST https://boards-server.herokuapp.com/users/

###

POST https://boards-server.herokuapp.com/users/login
Content-Type: application/json

{
    "email": "njuguna@mail.com",
    "pwd": "Patch"
}

####

POST https://boards-server.herokuapp.com/users/register
Content-Type: application/json

{
    "email": "kelvin@mail.com",
    "fname": "Kelvin",
    "lname": "Njuguna",
    "ts": "2020-05-19 11:25:25",
    "pwd": "Njuguna"
}

###
POST https://boards-server.herokuapp.com/users/register
Content-Type: application/json

{
    "email": "brian@mail.com",
    "fname": "Brian",
    "lname": "Munyu",
    "ts": "2020-05-19 11:25:25",
    "pwd": "Patch"
}

###

POST https://boards-server.herokuapp.com/users/searchUser
Content-Type: application/json

{
    "name": "brian"
}
###
GET https://boards-server.herokuapp.com/posts
#####

GET https://boards-server.herokuapp.com/posts/all
Content-Type: application/json

{
    "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5qdWd1bmFAbWFpbC5jb20iLCJmbmFtZSI6Ik5qZW5nYSIsImlhdCI6MTU5MTEyNTc3OX0.qElSp2_eS9kK1ZqW_FYCPp9_GD6RAMZuRH8GdA2rmJs",
    "other": {
        "fsd":"sdfs"
    }
}

###

POST https://boards-server.herokuapp.com/posts/new
Content-Type: application/json

{
    "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5qdWd1bmFAbWFpbC5jb20iLCJmbmFtZSI6Ik5qZW5nYSIsImlhdCI6MTU5MTEyNTc3OX0.qElSp2_eS9kK1ZqW_FYCPp9_GD6RAMZuRH8GdA2rmJs",
    "payload": {
        "userId": "2",
        "title": "FIRST ANNOUNCEMENT ON BOARDS",
        "content": "Content of the announcement",
        "ts": "2020-05-19 11:25:25"
    }
}
