GET http://localhost:3000/users/

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "njuguna@mail.com",
    "pwd": "Patch"
}

####

POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "njuguna@mail.com",
    "fname": "Brian",
    "lname": "Munyu",
    "ts": "2020-05-19 11:25:25",
    "pwd": "Patch"
}

###

POST http://localhost:3000/users/searchUser
Content-Type: application/json

{
    "name": "brian"
}
#####

GET http://localhost:3000/posts/all
Content-Type: application/json

{
    "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5qdWd1bmFAbWFpbC5jb20iLCJmbmFtZSI6Ik5qZW5nYSIsImlhdCI6MTU5MTEyNTc3OX0.qElSp2_eS9kK1ZqW_FYCPp9_GD6RAMZuRH8GdA2rmJs",
    "other": {
        "fsd":"sdfs"
    }
}

###

POST http://localhost:3000/posts/new
Content-Type: application/json

{
    "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5qdWd1bmFAbWFpbC5jb20iLCJmbmFtZSI6Ik5qZW5nYSIsImlhdCI6MTU5MTEyNTc3OX0.qElSp2_eS9kK1ZqW_FYCPp9_GD6RAMZuRH8GdA2rmJs",
    "payload": {
        "userId": "2",
        "title": "FIRST ANNOUNCEMENT ON BOARDS",
        "content": "Content of the announcement",
        "ts": "2020-05-19 11:25:25"
    }
}

###

GET http://localhost:3000/user/followers/Munyu_Brianlajd5zw3c5a

###
GET http://localhost:3000/user/following/Njuguna_Kelvinoavkb15ozhj
